language: python
python:
  - "2.7"
script: PYTHONHASHSEED=random python setup.py test
install:
  - sudo apt-get update
  - sudo apt-get install -qq git python-setuptools python-gevent python-fastimport python-mock
