---
name: Disperse configuration

"on":
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: jelmer/action-disperse-validate@v2.0.0
